" Global Settings: {{{

if !exists("g:abivim_color_custom")
    let g:abivim_color_custom = 0
endif

if !exists("g:abivim_supercomment")
    let g:abivim_supercomment = 1
endif



" > Variable-type-free colors

if !exists("g:abivim_color_repeatfg")
    let g:abivim_color_repeatfg = "#b5bfe2"
endif

if !exists("g:abivim_color_repeatbg")
    let g:abivim_color_repeatbg = "#e78284"
endif

if !exists("g:abivim_color_supercomment")
    let g:abivim_color_supercomment = "#a6d189"
endif

if !exists("g:abivim_link_repeat")
    let g:abivim_link_repeat = "Error"
endif
" }}}
" > Colors options

" Colors Settings: {{{
" ! PUSH AT THE END OF FILE !

" >>Customs
if g:abivim_color_custom
    if !exists("g:abivim_color_basic")
        let g:abivim_color_basic = "#ef9f76"
    endif
    if !exists("g:abivim_color_bse")
        let g:abivim_color_bse = "#ef9f76"
    endif
    if !exists("g:abivim_color_dev")
        let g:abivim_color_dev = "#ef9f76"
    endif
    if !exists("g:abivim_color_dfpt")
        let g:abivim_color_dfpt = "#ef9f76"
    endif
    if !exists("g:abivim_color_dmft")
        let g:abivim_color_dmft = "#ef9f76"
    endif
    if !exists("g:abivim_color_eph")
        let g:abivim_color_eph = "#ef9f76"
    endif
    if !exists("g:abivim_color_ffield")
        let g:abivim_color_ffield = "#ef9f76"
    endif
    if !exists("g:abivim_color_files")
        let g:abivim_color_files = "#ef9f76"
    endif
    if !exists("g:abivim_color_geo")
        let g:abivim_color_geo = "#ef9f76"
    endif
    if !exists("g:abivim_color_gstate")
        let g:abivim_color_gstate = "#ef9f76"
    endif
    if !exists("g:abivim_color_gw")
        let g:abivim_color_gw = "#ef9f76"
    endif
    if !exists("g:abivim_color_gwr")
        let g:abivim_color_gwr = "#ef9f76"
    endif
    if !exists("g:abivim_color_internal")
        let g:abivim_color_internal = "#ef9f76"
    endif
    if !exists("g:abivim_color_paral")
        let g:abivim_color_paral = "#ef9f76"
    endif
    if !exists("g:abivim_color_paw")
        let g:abivim_color_paw = "#ef9f76"
    endif
    if !exists("g:abivim_color_rlx")
        let g:abivim_color_rlx = "#ef9f76"
    endif
    if !exists("g:abivim_color_rttddft")
        let g:abivim_color_rttddft = "#ef9f76"
    endif
    if !exists("g:abivim_color_vdw")
        let g:abivim_color_vdw = "#ef9f76"
    endif
    if !exists("g:abivim_color_w90")
        let g:abivim_color_w90 = "#ef9f76"
    endif

else
" >>Linkers
    if !exists("g:abivim_link_basic")
    let g:abivim_link_basic = "Keyword"
    endif
    if !exists("g:abivim_link_bse")
    let g:abivim_link_bse = "Keyword"
    endif
    if !exists("g:abivim_link_dev")
    let g:abivim_link_dev = "Keyword"
    endif
    if !exists("g:abivim_link_dfpt")
    let g:abivim_link_dfpt = "Keyword"
    endif
    if !exists("g:abivim_link_dmft")
    let g:abivim_link_dmft = "Keyword"
    endif
    if !exists("g:abivim_link_eph")
    let g:abivim_link_eph = "Keyword"
    endif
    if !exists("g:abivim_link_ffield")
    let g:abivim_link_ffield = "Keyword"
    endif
    if !exists("g:abivim_link_files")
    let g:abivim_link_files = "Keyword"
    endif
    if !exists("g:abivim_link_geo")
    let g:abivim_link_geo = "Keyword"
    endif
    if !exists("g:abivim_link_gstate")
    let g:abivim_link_gstate = "Keyword"
    endif
    if !exists("g:abivim_link_gw")
    let g:abivim_link_gw = "Keyword"
    endif
    if !exists("g:abivim_link_gwr")
    let g:abivim_link_gwr = "Keyword"
    endif
    if !exists("g:abivim_link_internal")
    let g:abivim_link_internal = "Keyword"
    endif
    if !exists("g:abivim_link_paral")
    let g:abivim_link_paral = "Keyword"
    endif
    if !exists("g:abivim_link_paw")
    let g:abivim_link_paw = "Keyword"
    endif
    if !exists("g:abivim_link_rlx")
    let g:abivim_link_rlx = "Keyword"
    endif
    if !exists("g:abivim_link_rttddft")
    let g:abivim_link_rttddft = "Keyword"
    endif
    if !exists("g:abivim_link_vdw")
    let g:abivim_link_vdw = "Keyword"
    endif
    if !exists("g:abivim_link_w90")
    let g:abivim_link_w90 = "Keyword"
    endif
endif

" }}}
" abinit input syntax file for vim
 
syntax region String start=/\v\"/ skip=/\v\\./ end=/\v\"/
syntax match Float "-\?[0-9\.]\+[dDeE0-9]\+\.\?"
syntax match Number "-\?[0-9]\+"

" ============================

" https://docs.abinit.org/guide/abinit/#physical-information
syntax keyword energy_unit Ha Hartree eV meV Rydbergs Rydberg Ry K Kelvin
syntax keyword length_unit Bohr nm Ang Angstr Angstrom angstrom
syntax keyword mag_unit T Tesla
syntax keyword time_unit as asec asecond ps psec psecond
highlight! link energy_unit Type
highlight! link length_unit Type
highlight! link time_unit Type
highlight! link mag_unit Type

" ============================

if g:abivim_color_custom
    exec 'highlight basic guifg= ' . g:abivim_color_basic
    exec 'highlight bse guifg= ' . g:abivim_color_bse
    exec 'highlight dev guifg= ' . g:abivim_color_dev
    exec 'highlight dfpt guifg= ' . g:abivim_color_dfpt
    exec 'highlight dmft guifg= ' . g:abivim_color_dmft
    exec 'highlight eph guifg= ' . g:abivim_color_eph
    exec 'highlight ffield guifg= ' . g:abivim_color_ffield
    exec 'highlight files guifg= ' . g:abivim_color_files
    exec 'highlight geo guifg= ' . g:abivim_color_geo
    exec 'highlight gstate guifg= ' . g:abivim_color_gstate
    exec 'highlight gw guifg= ' . g:abivim_color_gw
    exec 'highlight gwr guifg= ' . g:abivim_color_gwr
    exec 'highlight internal guifg= ' . g:abivim_color_internal
    exec 'highlight paral guifg= ' . g:abivim_color_paral
    exec 'highlight paw guifg= ' . g:abivim_color_paw
    exec 'highlight rlx guifg= ' . g:abivim_color_rlx
    exec 'highlight rttddft guifg= ' . g:abivim_color_rttddft
    exec 'highlight vdw guifg= ' . g:abivim_color_vdw
    exec 'highlight w90 guifg= ' . g:abivim_color_w90
    exec 'highlight Repeat guifg= ' . g:abivim_color_repeatfg . ' guibg=' . g:abivim_color_repeatbg
else
    exec 'highlight! link basic ' . g:abivim_link_basic
    exec 'highlight! link bse ' . g:abivim_link_bse
    exec 'highlight! link dev ' . g:abivim_link_dev
    exec 'highlight! link dfpt ' . g:abivim_link_dfpt
    exec 'highlight! link dmft ' . g:abivim_link_dmft
    exec 'highlight! link eph ' . g:abivim_link_eph
    exec 'highlight! link ffield ' . g:abivim_link_ffield
    exec 'highlight! link files ' . g:abivim_link_files
    exec 'highlight! link geo ' . g:abivim_link_geo
    exec 'highlight! link gstate ' . g:abivim_link_gstate
    exec 'highlight! link gw ' . g:abivim_link_gw
    exec 'highlight! link gwr ' . g:abivim_link_gwr
    exec 'highlight! link internal ' . g:abivim_link_internal
    exec 'highlight! link paral ' . g:abivim_link_paral
    exec 'highlight! link paw ' . g:abivim_link_paw
    exec 'highlight! link rlx ' . g:abivim_link_rlx
    exec 'highlight! link rttddft ' . g:abivim_link_rttddft
    exec 'highlight! link vdw ' . g:abivim_link_vdw
    exec 'highlight! link w90 ' . g:abivim_link_w90
    exec 'highlight! link Repeat ' . g:abivim_link_repeat
endif

" ============================

syntax match basic "\<accuracy[0-9:?+]*\c\>"
syntax match basic "\<acell[0-9:?+]*\c\>"
syntax match rlx "\<adpimd[0-9:?+]*\c\>"
syntax match rlx "\<adpimd_gamma[0-9:?+]*\c\>"
syntax match gstate "\<algalch[0-9:?+]*\c\>"
syntax match rlx "\<amu[0-9:?+]*\c\>"
syntax match basic "\<angdeg[0-9:?+]*\c\>"
syntax match dfpt "\<asr[0-9:?+]*\c\>"
syntax match ffield "\<atvshift[0-9:?+]*\c\>"
syntax match paral "\<autoparal[0-9:?+]*\c\>"
syntax match gstate "\<auxc_ixc[0-9:?+]*\c\>"
syntax match gstate "\<auxc_scal[0-9:?+]*\c\>"
syntax match gw "\<awtr[0-9:?+]*\c\>"
syntax match paral "\<bandpp[0-9:?+]*\c\>"
syntax match ffield "\<bdberry[0-9:?+]*\c\>"
syntax match dfpt "\<bdeigrf[0-9:?+]*\c\>"
syntax match gw "\<bdgw[0-9:?+]*\c\>"
syntax match ffield "\<berryopt[0-9:?+]*\c\>"
syntax match ffield "\<berrysav[0-9:?+]*\c\>"
syntax match ffield "\<berrystep[0-9:?+]*\c\>"
syntax match ffield "\<bfield[0-9:?+]*\c\>"
syntax match rlx "\<bmass[0-9:?+]*\c\>"
syntax match gstate "\<boxcenter[0-9:?+]*\c\>"
syntax match gstate "\<boxcutmin[0-9:?+]*\c\>"
syntax match geo "\<brvltt[0-9:?+]*\c\>"
syntax match bse "\<bs_algorithm[0-9:?+]*\c\>"
syntax match bse "\<bs_calctype[0-9:?+]*\c\>"
syntax match bse "\<bs_coulomb_term[0-9:?+]*\c\>"
syntax match bse "\<bs_coupling[0-9:?+]*\c\>"
syntax match bse "\<bs_eh_cutoff[0-9:?+]*\c\>"
syntax match bse "\<bs_exchange_term[0-9:?+]*\c\>"
syntax match bse "\<bs_freq_mesh[0-9:?+]*\c\>"
syntax match bse "\<bs_hayd_term[0-9:?+]*\c\>"
syntax match bse "\<bs_haydock_niter[0-9:?+]*\c\>"
syntax match bse "\<bs_haydock_tol[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_kmult[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_m3_width[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_method[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_mode[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_prep[0-9:?+]*\c\>"
syntax match bse "\<bs_interp_rl_nb[0-9:?+]*\c\>"
syntax match bse "\<bs_loband[0-9:?+]*\c\>"
syntax match bse "\<bs_nstates[0-9:?+]*\c\>"
syntax match dev "\<builtintest[0-9:?+]*\c\>"
syntax match paw "\<bxctmindg[0-9:?+]*\c\>"
syntax match gw "\<cd_customnimfrqs[0-9:?+]*\c\>"
syntax match gw "\<cd_frqim_method[0-9:?+]*\c\>"
syntax match gw "\<cd_full_grid[0-9:?+]*\c\>"
syntax match gw "\<cd_halfway_freq[0-9:?+]*\c\>"
syntax match gw "\<cd_imfrqs[0-9:?+]*\c\>"
syntax match gw "\<cd_max_freq[0-9:?+]*\c\>"
syntax match gw "\<cd_subset_freq[0-9:?+]*\c\>"
syntax match gstate "\<cellcharge[0-9:?+]*\c\>"
syntax match gstate "\<charge[0-9:?+]*\c\>"
syntax match gstate "\<chebfi_oracle[0-9:?+]*\c\>"
syntax match geo "\<chempot[0-9:?+]*\c\>"
syntax match rlx "\<chkdilatmx[0-9:?+]*\c\>"
syntax match gstate "\<chkexit[0-9:?+]*\c\>"
syntax match gstate "\<chkparal[0-9:?+]*\c\>"
syntax match gstate "\<chkprim[0-9:?+]*\c\>"
syntax match gstate "\<chksymbreak[0-9:?+]*\c\>"
syntax match gstate "\<chksymtnons[0-9:?+]*\c\>"
syntax match dfpt "\<chneut[0-9:?+]*\c\>"
syntax match gstate "\<chrgat[0-9:?+]*\c\>"
syntax match rlx "\<cineb_start[0-9:?+]*\c\>"
syntax match gstate "\<constraint_kind[0-9:?+]*\c\>"
syntax match gstate "\<cprj_in_memory[0-9:?+]*\c\>"
syntax match dev "\<cprj_update_lvl[0-9:?+]*\c\>"
syntax match gstate "\<cpuh[0-9:?+]*\c\>"
syntax match gstate "\<cpum[0-9:?+]*\c\>"
syntax match gstate "\<cpus[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert1_atpol[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert1_dir[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert1_elfd[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert1_phon[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert2_atpol[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert2_dir[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert2_elfd[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert2_phon[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert3_atpol[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert3_dir[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert3_elfd[0-9:?+]*\c\>"
syntax match dfpt "\<d3e_pert3_phon[0-9:?+]*\c\>"
syntax match ffield "\<ddamp[0-9:?+]*\c\>"
syntax match eph "\<ddb_ngqpt[0-9:?+]*\c\>"
syntax match eph "\<ddb_shiftq[0-9:?+]*\c\>"
syntax match rlx "\<delayperm[0-9:?+]*\c\>"
syntax match dev "\<densfor_pred[0-9:?+]*\c\>"
syntax match dev "\<densty[0-9:?+]*\c\>"
syntax match ffield "\<dfield[0-9:?+]*\c\>"
syntax match dfpt "\<dfpt_sciss[0-9:?+]*\c\>"
syntax match gstate "\<diecut[0-9:?+]*\c\>"
syntax match gstate "\<diegap[0-9:?+]*\c\>"
syntax match gstate "\<dielam[0-9:?+]*\c\>"
syntax match gstate "\<dielng[0-9:?+]*\c\>"
syntax match gstate "\<diemac[0-9:?+]*\c\>"
syntax match gstate "\<diemix[0-9:?+]*\c\>"
syntax match gstate "\<diemixmag[0-9:?+]*\c\>"
syntax match rlx "\<diismemory[0-9:?+]*\c\>"
syntax match rlx "\<dilatmx[0-9:?+]*\c\>"
syntax match eph "\<dipdip[0-9:?+]*\c\>"
syntax match paw "\<dmatpawu[0-9:?+]*\c\>"
syntax match paw "\<dmatpuopt[0-9:?+]*\c\>"
syntax match paw "\<dmatudiag[0-9:?+]*\c\>"
syntax match dmft "\<dmft_charge_prec[0-9:?+]*\c\>"
syntax match dmft "\<dmft_dc[0-9:?+]*\c\>"
syntax match dmft "\<dmft_entropy[0-9:?+]*\c\>"
syntax match dmft "\<dmft_kspectral_func[0-9:?+]*\c\>"
syntax match dmft "\<dmft_iter[0-9:?+]*\c\>"
syntax match dmft "\<dmft_mxsf[0-9:?+]*\c\>"
syntax match dmft "\<dmft_nlambda[0-9:?+]*\c\>"
syntax match dmft "\<dmft_nwli[0-9:?+]*\c\>"
syntax match dmft "\<dmft_nwlo[0-9:?+]*\c\>"
syntax match dmft "\<dmft_occnd_imag[0-9:?+]*\c\>"
syntax match dev "\<dmft_read_occnd[0-9:?+]*\c\>"
syntax match dmft "\<dmft_rslf[0-9:?+]*\c\>"
syntax match dmft "\<dmft_solv[0-9:?+]*\c\>"
syntax match dmft "\<dmft_t2g[0-9:?+]*\c\>"
syntax match dmft "\<dmft_tolfreq[0-9:?+]*\c\>"
syntax match dmft "\<dmft_tollc[0-9:?+]*\c\>"
syntax match dmft "\<dmft_wanorthnorm[0-9:?+]*\c\>"
syntax match dmft "\<dmftbandf[0-9:?+]*\c\>"
syntax match dmft "\<dmftbandi[0-9:?+]*\c\>"
syntax match dmft "\<dmftcheck[0-9:?+]*\c\>"
syntax match dev "\<dmftctqmc_basis[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_check[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_correl[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_config[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_gmove[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_grnns[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_meas[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_mov[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_mrka[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_order[0-9:?+]*\c\>"
syntax match dmft "\<dmftctqmc_triqs_nleg[0-9:?+]*\c\>"
syntax match dmft "\<dmftqmc_l[0-9:?+]*\c\>"
syntax match dmft "\<dmftqmc_n[0-9:?+]*\c\>"
syntax match dmft "\<dmftqmc_seed[0-9:?+]*\c\>"
syntax match dmft "\<dmftqmc_therm[0-9:?+]*\c\>"
syntax match gstate "\<dosdeltae[0-9:?+]*\c\>"
syntax match rttddft "\<dtele[0-9:?+]*\c\>"
syntax match rlx "\<dtion[0-9:?+]*\c\>"
syntax match rlx "\<dynimage[0-9:?+]*\c\>"
syntax match basic "\<ecut[0-9:?+]*\c\>"
syntax match gw "\<ecuteps[0-9:?+]*\c\>"
syntax match gw "\<ecutsigx[0-9:?+]*\c\>"
syntax match rlx "\<ecutsm[0-9:?+]*\c\>"
syntax match gw "\<ecutwfn[0-9:?+]*\c\>"
syntax match dev "\<effmass_free[0-9:?+]*\c\>"
syntax match ffield "\<efield[0-9:?+]*\c\>"
syntax match dfpt "\<efmas[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_bands[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_calc_dirs[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_deg[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_deg_tol[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_dim[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_dirs[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_n_dirs[0-9:?+]*\c\>"
syntax match dfpt "\<efmas_ntheta[0-9:?+]*\c\>"
syntax match basic "\<einterp[0-9:?+]*\c\>"
syntax match dfpt "\<elph2_imagden[0-9:?+]*\c\>"
syntax match gstate "\<enunit[0-9:?+]*\c\>"
syntax match eph "\<eph_ahc_type[0-9:?+]*\c\>"
syntax match eph "\<eph_extrael[0-9:?+]*\c\>"
syntax match eph "\<eph_fermie[0-9:?+]*\c\>"
syntax match eph "\<eph_frohlichm[0-9:?+]*\c\>"
syntax match eph "\<eph_frohl_ntheta[0-9:?+]*\c\>"
syntax match eph "\<eph_fsewin[0-9:?+]*\c\>"
syntax match eph "\<eph_fsmear[0-9:?+]*\c\>"
syntax match eph "\<eph_intmeth[0-9:?+]*\c\>"
syntax match eph "\<eph_mustar[0-9:?+]*\c\>"
syntax match eph "\<eph_ngqpt_fine[0-9:?+]*\c\>"
syntax match eph "\<eph_task[0-9:?+]*\c\>"
syntax match eph "\<eph_transport[0-9:?+]*\c\>"
syntax match dev "\<eshift[0-9:?+]*\c\>"
syntax match dfpt "\<esmear[0-9:?+]*\c\>"
syntax match dev "\<exchmix[0-9:?+]*\c\>"
syntax match dev "\<exchn2n3d[0-9:?+]*\c\>"
syntax match gstate "\<expert_user[0-9:?+]*\c\>"
syntax match dev "\<extrapwf[0-9:?+]*\c\>"
syntax match paw "\<f4of2_sla[0-9:?+]*\c\>"
syntax match paw "\<f6of2_sla[0-9:?+]*\c\>"
syntax match gstate "\<fband[0-9:?+]*\c\>"
syntax match dev "\<fermie_nest[0-9:?+]*\c\>"
syntax match dfpt "\<ffnl_lw[0-9:?+]*\c\>"
syntax match dev "\<fftalg[0-9:?+]*\c\>"
syntax match dev "\<fftcache[0-9:?+]*\c\>"
syntax match dev "\<fft_count[0-9:?+]*\c\>"
syntax match gw "\<fftgw[0-9:?+]*\c\>"
syntax match ffield "\<field_red[0-9:?+]*\c\>"
syntax match gstate "\<fockdownsampling[0-9:?+]*\c\>"
syntax match gstate "\<fock_icutcoul[0-9:?+]*\c\>"
syntax match gstate "\<fockoptmix[0-9:?+]*\c\>"
syntax match gw "\<freqim_alpha[0-9:?+]*\c\>"
syntax match gw "\<freqremax[0-9:?+]*\c\>"
syntax match gw "\<freqremin[0-9:?+]*\c\>"
syntax match gw "\<freqspmax[0-9:?+]*\c\>"
syntax match gw "\<freqspmin[0-9:?+]*\c\>"
syntax match rlx "\<friction[0-9:?+]*\c\>"
syntax match rlx "\<frictionbar[0-9:?+]*\c\>"
syntax match dfpt "\<frzfermi[0-9:?+]*\c\>"
syntax match rlx "\<fxcartfactor[0-9:?+]*\c\>"
syntax match rlx "\<ga_algor[0-9:?+]*\c\>"
syntax match rlx "\<ga_fitness[0-9:?+]*\c\>"
syntax match rlx "\<ga_n_rules[0-9:?+]*\c\>"
syntax match rlx "\<ga_opt_percent[0-9:?+]*\c\>"
syntax match rlx "\<ga_rules[0-9:?+]*\c\>"
syntax match geo "\<genafm[0-9:?+]*\c\>"
syntax match rlx "\<geoopt[0-9:?+]*\c\>"
syntax match files "\<get1den[0-9:?+]*\c\>"
syntax match files "\<get1wf[0-9:?+]*\c\>"
syntax match files "\<getbscoup[0-9:?+]*\c\>"
syntax match files "\<getbseig[0-9:?+]*\c\>"
syntax match files "\<getbsreso[0-9:?+]*\c\>"
syntax match rlx "\<getcell[0-9:?+]*\c\>"
syntax match files "\<getddb[0-9:?+]*\c\>"
syntax match files "\<getddk[0-9:?+]*\c\>"
syntax match files "\<getdelfd[0-9:?+]*\c\>"
syntax match files "\<getden[0-9:?+]*\c\>"
syntax match files "\<getdkde[0-9:?+]*\c\>"
syntax match files "\<getdkdk[0-9:?+]*\c\>"
syntax match files "\<getdvdb[0-9:?+]*\c\>"
syntax match files "\<getefmas[0-9:?+]*\c\>"
syntax match dev "\<getgam_eig2nkq[0-9:?+]*\c\>"
syntax match files "\<gethaydock[0-9:?+]*\c\>"
syntax match files "\<getkden[0-9:?+]*\c\>"
syntax match files "\<getocc[0-9:?+]*\c\>"
syntax match files "\<getqps[0-9:?+]*\c\>"
syntax match files "\<getscr[0-9:?+]*\c\>"
syntax match files "\<getsuscep[0-9:?+]*\c\>"
syntax match rlx "\<getvel[0-9:?+]*\c\>"
syntax match files "\<getwfk[0-9:?+]*\c\>"
syntax match dev "\<getwfkfine[0-9:?+]*\c\>"
syntax match files "\<getwfq[0-9:?+]*\c\>"
syntax match rlx "\<getxcart[0-9:?+]*\c\>"
syntax match rlx "\<getxred[0-9:?+]*\c\>"
syntax match rlx "\<goprecon[0-9:?+]*\c\>"
syntax match rlx "\<goprecprm[0-9:?+]*\c\>"
syntax match paral "\<gpu_devices[0-9:?+]*\c\>"
syntax match paral "\<gpu_kokkos_nthrd[0-9:?+]*\c\>"
syntax match paral "\<gpu_linalg_limit[0-9:?+]*\c\>"
syntax match paral "\<gpu_nl_distrib[0-9:?+]*\c\>"
syntax match paral "\<gpu_nl_splitsize[0-9:?+]*\c\>"
syntax match paral "\<gpu_option[0-9:?+]*\c\>"
syntax match paral "\<gpu_thread_limit[0-9:?+]*\c\>"
syntax match gw "\<gw_customnfreqsp[0-9:?+]*\c\>"
syntax match gw "\<gw_freqsp[0-9:?+]*\c\>"
syntax match gw "\<gw_frqim_inzgrid[0-9:?+]*\c\>"
syntax match gw "\<gw_frqre_inzgrid[0-9:?+]*\c\>"
syntax match gw "\<gw_frqre_tangrid[0-9:?+]*\c\>"
syntax match gw "\<gw_icutcoul[0-9:?+]*\c\>"
syntax match gw "\<gw_invalid_freq[0-9:?+]*\c\>"
syntax match gw "\<gw_nqlwl[0-9:?+]*\c\>"
syntax match gwr "\<gwr_nstep[0-9:?+]*\c\>"
syntax match gwr "\<gwr_fit[0-9:?+]*\c\>"
syntax match gw "\<gw_qlwl[0-9:?+]*\c\>"
syntax match gw "\<gw_qprange[0-9:?+]*\c\>"
syntax match gw "\<gw_sigxcore[0-9:?+]*\c\>"
syntax match gwr "\<gwr_tolqpe[0-9:?+]*\c\>"
syntax match gw "\<gw1rdm[0-9:?+]*\c\>"
syntax match gw "\<gwaclowrank[0-9:?+]*\c\>"
syntax match gw "\<gwcalctyp[0-9:?+]*\c\>"
syntax match gw "\<gwcomp[0-9:?+]*\c\>"
syntax match gw "\<gwencomp[0-9:?+]*\c\>"
syntax match gw "\<gwgamma[0-9:?+]*\c\>"
syntax match gw "\<gwgmcorr[0-9:?+]*\c\>"
syntax match gw "\<gwls_band_index[0-9:?+]*\c\>"
syntax match gw "\<gwls_correlation[0-9:?+]*\c\>"
syntax match gw "\<gwls_diel_model[0-9:?+]*\c\>"
syntax match gw "\<gwls_exchange[0-9:?+]*\c\>"
syntax match gw "\<gwls_first_seed[0-9:?+]*\c\>"
syntax match gw "\<gwls_kmax_analytic[0-9:?+]*\c\>"
syntax match gw "\<gwls_kmax_complement[0-9:?+]*\c\>"
syntax match gw "\<gwls_kmax_numeric[0-9:?+]*\c\>"
syntax match gw "\<gwls_kmax_poles[0-9:?+]*\c\>"
syntax match gw "\<gwls_list_proj_freq[0-9:?+]*\c\>"
syntax match gw "\<gwls_model_parameter[0-9:?+]*\c\>"
syntax match gw "\<gwls_n_proj_freq[0-9:?+]*\c\>"
syntax match gw "\<gwls_npt_gauss_quad[0-9:?+]*\c\>"
syntax match gw "\<gwls_nseeds[0-9:?+]*\c\>"
syntax match gw "\<gwls_print_debug[0-9:?+]*\c\>"
syntax match gw "\<gwls_recycle[0-9:?+]*\c\>"
syntax match gw "\<gwls_stern_kmax[0-9:?+]*\c\>"
syntax match gw "\<gwmem[0-9:?+]*\c\>"
syntax match paral "\<gwpara[0-9:?+]*\c\>"
syntax match gw "\<gwrpacorr[0-9:?+]*\c\>"
syntax match rlx "\<hmctt[0-9:?+]*\c\>"
syntax match rlx "\<hmcsst[0-9:?+]*\c\>"
syntax match gstate "\<hyb_mixing[0-9:?+]*\c\>"
syntax match gstate "\<hyb_mixing_sr[0-9:?+]*\c\>"
syntax match gstate "\<hyb_range_dft[0-9:?+]*\c\>"
syntax match gstate "\<hyb_range_fock[0-9:?+]*\c\>"
syntax match rlx "\<iatcon[0-9:?+]*\c\>"
syntax match rlx "\<iatfix[0-9:?+]*\c\>"
syntax match rlx "\<iatfixx[0-9:?+]*\c\>"
syntax match rlx "\<iatfixy[0-9:?+]*\c\>"
syntax match rlx "\<iatfixz[0-9:?+]*\c\>"
syntax match gstate "\<iatsph[0-9:?+]*\c\>"
syntax match paw "\<iboxcut[0-9:?+]*\c\>"
syntax match gstate "\<icoulomb[0-9:?+]*\c\>"
syntax match gstate "\<icutcoul[0-9:?+]*\c\>"
syntax match dfpt "\<ieig2rf[0-9:?+]*\c\>"
syntax match rlx "\<imgmov[0-9:?+]*\c\>"
syntax match rlx "\<imgwfstor[0-9:?+]*\c\>"
syntax match gw "\<inclvkb[0-9:?+]*\c\>"
syntax match dev "\<intxc[0-9:?+]*\c\>"
syntax match dev "\<invovl_blksliced[0-9:?+]*\c\>"
syntax match dev "\<iomode[0-9:?+]*\c\>"
syntax match dev "\<ionmov[0-9:?+]*\c\>"
syntax match gstate "\<iprcel[0-9:?+]*\c\>"
syntax match dev "\<iprcfc[0-9:?+]*\c\>"
syntax match gstate "\<iqpt[0-9:?+]*\c\>"
syntax match dev "\<irandom[0-9:?+]*\c\>"
syntax match files "\<ird1den[0-9:?+]*\c\>"
syntax match files "\<ird1wf[0-9:?+]*\c\>"
syntax match files "\<irdbscoup[0-9:?+]*\c\>"
syntax match files "\<irdbseig[0-9:?+]*\c\>"
syntax match files "\<irdbsreso[0-9:?+]*\c\>"
syntax match files "\<irdchkprdm[0-9:?+]*\c\>"
syntax match files "\<irdddb[0-9:?+]*\c\>"
syntax match files "\<irdddk[0-9:?+]*\c\>"
syntax match files "\<irdden[0-9:?+]*\c\>"
syntax match files "\<irdkden[0-9:?+]*\c\>"
syntax match files "\<irddvdb[0-9:?+]*\c\>"
syntax match files "\<irdefmas[0-9:?+]*\c\>"
syntax match files "\<irdhaydock[0-9:?+]*\c\>"
syntax match files "\<irdqps[0-9:?+]*\c\>"
syntax match files "\<irdscr[0-9:?+]*\c\>"
syntax match files "\<irdsuscep[0-9:?+]*\c\>"
syntax match vdw "\<irdvdw[0-9:?+]*\c\>"
syntax match files "\<irdwfk[0-9:?+]*\c\>"
syntax match dev "\<irdwfkfine[0-9:?+]*\c\>"
syntax match files "\<irdwfq[0-9:?+]*\c\>"
syntax match basic "\<iscf[0-9:?+]*\c\>"
syntax match dev "\<isecur[0-9:?+]*\c\>"
syntax match rlx "\<istatimg[0-9:?+]*\c\>"
syntax match dev "\<istatr[0-9:?+]*\c\>"
syntax match dev "\<istatshft[0-9:?+]*\c\>"
syntax match dev "\<istwfk[0-9:?+]*\c\>"
syntax match gstate "\<ivalence[0-9:?+]*\c\>"
syntax match basic "\<ixc[0-9:?+]*\c\>"
syntax match gw "\<ixc_sigma[0-9:?+]*\c\>"
syntax match gstate "\<ixcpositron[0-9:?+]*\c\>"
syntax match dfpt "\<ixcrot[0-9:?+]*\c\>"
syntax match basic "\<jdtset[0-9:?+]*\c\>"
syntax match gstate "\<jellslab[0-9:?+]*\c\>"
syntax match ffield "\<jfielddir[0-9:?+]*\c\>"
syntax match paw "\<jpawu[0-9:?+]*\c\>"
syntax match ffield "\<kberry[0-9:?+]*\c\>"
syntax match basic "\<kpt[0-9:?+]*\c\>"
syntax match gstate "\<kptbounds[0-9:?+]*\c\>"
syntax match gw "\<kptgw[0-9:?+]*\c\>"
syntax match basic "\<kptnrm[0-9:?+]*\c\>"
syntax match internal "\<kptns[0-9:?+]*\c\>"
syntax match internal "\<kptns_hf[0-9:?+]*\c\>"
syntax match basic "\<kptopt[0-9:?+]*\c\>"
syntax match gstate "\<kptrlatt[0-9:?+]*\c\>"
syntax match gstate "\<kptrlen[0-9:?+]*\c\>"
syntax match files "\<kssform[0-9:?+]*\c\>"
syntax match paw "\<lambsig[0-9:?+]*\c\>"
syntax match paw "\<ldaminushalf[0-9:?+]*\c\>"
syntax match paw "\<lexexch[0-9:?+]*\c\>"
syntax match paral "\<localrdwf[0-9:?+]*\c\>"
syntax match dev "\<lotf_classic[0-9:?+]*\c\>"
syntax match dev "\<lotf_nitex[0-9:?+]*\c\>"
syntax match dev "\<lotf_nneigx[0-9:?+]*\c\>"
syntax match dev "\<lotf_version[0-9:?+]*\c\>"
syntax match paw "\<lpawu[0-9:?+]*\c\>"
syntax match dfpt "\<lw_flexo[0-9:?+]*\c\>"
syntax match dfpt "\<lw_natopt[0-9:?+]*\c\>"
syntax match dfpt "\<lw_qdrpl[0-9:?+]*\c\>"
syntax match dev "\<macro_uj[0-9:?+]*\c\>"
syntax match gstate "\<magcon_lambda[0-9:?+]*\c\>"
syntax match gstate "\<magconon[0-9:?+]*\c\>"
syntax match paral "\<max_ncpus[0-9:?+]*\c\>"
syntax match ffield "\<maxestep[0-9:?+]*\c\>"
syntax match dev "\<maxnsym[0-9:?+]*\c\>"
syntax match internal "\<mband[0-9:?+]*\c\>"
syntax match gw "\<mbpt_sciss[0-9:?+]*\c\>"
syntax match gstate "\<mdeg_filter[0-9:?+]*\c\>"
syntax match gw "\<mdf_epsinf[0-9:?+]*\c\>"
syntax match rlx "\<mdtemp[0-9:?+]*\c\>"
syntax match rlx "\<mdwall[0-9:?+]*\c\>"
syntax match dev "\<mem_test[0-9:?+]*\c\>"
syntax match rlx "\<mep_mxstep[0-9:?+]*\c\>"
syntax match rlx "\<mep_solver[0-9:?+]*\c\>"
syntax match dev "\<mixprec[0-9:?+]*\c\>"
syntax match internal "\<mgfft[0-9:?+]*\c\>"
syntax match internal "\<mgfftdg[0-9:?+]*\c\>"
syntax match gstate "\<mixalch[0-9:?+]*\c\>"
syntax match rlx "\<mixesimgf[0-9:?+]*\c\>"
syntax match rlx "\<moldyn[0-9:?+]*\c\>"
syntax match internal "\<mpw[0-9:?+]*\c\>"
syntax match dev "\<mqgrid[0-9:?+]*\c\>"
syntax match paw "\<mqgriddg[0-9:?+]*\c\>"
syntax match rlx "\<natcon[0-9:?+]*\c\>"
syntax match rlx "\<natfix[0-9:?+]*\c\>"
syntax match rlx "\<natfixx[0-9:?+]*\c\>"
syntax match rlx "\<natfixy[0-9:?+]*\c\>"
syntax match rlx "\<natfixz[0-9:?+]*\c\>"
syntax match basic "\<natom[0-9:?+]*\c\>"
syntax match internal "\<natpawu[0-9:?+]*\c\>"
syntax match geo "\<natrd[0-9:?+]*\c\>"
syntax match gstate "\<natsph[0-9:?+]*\c\>"
syntax match gstate "\<natsph_extra[0-9:?+]*\c\>"
syntax match ffield "\<natvshift[0-9:?+]*\c\>"
syntax match basic "\<nband[0-9:?+]*\c\>"
syntax match basic "\<nbandhf[0-9:?+]*\c\>"
syntax match gw "\<nbandkss[0-9:?+]*\c\>"
syntax match dev "\<nbdblock[0-9:?+]*\c\>"
syntax match gstate "\<nbdbuf[0-9:?+]*\c\>"
syntax match ffield "\<nberry[0-9:?+]*\c\>"
syntax match gstate "\<nblock_lobpcg[0-9:?+]*\c\>"
syntax match dev "\<nc_xccc_gspace[0-9:?+]*\c\>"
syntax match rlx "\<nconeq[0-9:?+]*\c\>"
syntax match files "\<ncout[0-9:?+]*\c\>"
syntax match dev "\<nctime[0-9:?+]*\c\>"
syntax match gstate "\<ndivk[0-9:?+]*\c\>"
syntax match gstate "\<ndivsm[0-9:?+]*\c\>"
syntax match basic "\<ndtset[0-9:?+]*\c\>"
syntax match internal "\<ndynimage[0-9:?+]*\c\>"
syntax match rlx "\<neb_algo[0-9:?+]*\c\>"
syntax match rlx "\<neb_cell_algo[0-9:?+]*\c\>"
syntax match rlx "\<neb_spring[0-9:?+]*\c\>"
syntax match internal "\<nelect[0-9:?+]*\c\>"
syntax match internal "\<nfft[0-9:?+]*\c\>"
syntax match internal "\<nfftdg[0-9:?+]*\c\>"
syntax match gw "\<nfreqim[0-9:?+]*\c\>"
syntax match gw "\<nfreqmidm[0-9:?+]*\c\>"
syntax match gw "\<nfreqre[0-9:?+]*\c\>"
syntax match gw "\<nfreqsp[0-9:?+]*\c\>"
syntax match gstate "\<ngfft[0-9:?+]*\c\>"
syntax match paw "\<ngfftdg[0-9:?+]*\c\>"
syntax match basic "\<ngkpt[0-9:?+]*\c\>"
syntax match gstate "\<ngqpt[0-9:?+]*\c\>"
syntax match rlx "\<nimage[0-9:?+]*\c\>"
syntax match basic "\<nkpath[0-9:?+]*\c\>"
syntax match basic "\<nkpt[0-9:?+]*\c\>"
syntax match gw "\<nkptgw[0-9:?+]*\c\>"
syntax match basic "\<nkpthf[0-9:?+]*\c\>"
syntax match gstate "\<nline[0-9:?+]*\c\>"
syntax match dev "\<nloc_alg[0-9:?+]*\c\>"
syntax match dev "\<nloc_mem[0-9:?+]*\c\>"
syntax match rlx "\<nnos[0-9:?+]*\c\>"
syntax match dev "\<nonlop_ylm_count[0-9:?+]*\c\>"
syntax match dev "\<nnsclo[0-9:?+]*\c\>"
syntax match dev "\<nnsclohf[0-9:?+]*\c\>"
syntax match geo "\<nobj[0-9:?+]*\c\>"
syntax match gw "\<nomegasf[0-9:?+]*\c\>"
syntax match gw "\<nomegasi[0-9:?+]*\c\>"
syntax match gw "\<nomegasrd[0-9:?+]*\c\>"
syntax match dfpt "\<nonlinear_info[0-9:?+]*\c\>"
syntax match dev "\<normpawu[0-9:?+]*\c\>"
syntax match rlx "\<noseinert[0-9:?+]*\c\>"
syntax match paral "\<np_slk[0-9:?+]*\c\>"
syntax match paral "\<npband[0-9:?+]*\c\>"
syntax match paral "\<npfft[0-9:?+]*\c\>"
syntax match paral "\<nphf[0-9:?+]*\c\>"
syntax match paral "\<npimage[0-9:?+]*\c\>"
syntax match paral "\<npkpt[0-9:?+]*\c\>"
syntax match paral "\<np_spkpt[0-9:?+]*\c\>"
syntax match paral "\<nppert[0-9:?+]*\c\>"
syntax match gstate "\<npsp[0-9:?+]*\c\>"
syntax match gstate "\<npspalch[0-9:?+]*\c\>"
syntax match paral "\<npspinor[0-9:?+]*\c\>"
syntax match dev "\<npulayit[0-9:?+]*\c\>"
syntax match gw "\<npvel[0-9:?+]*\c\>"
syntax match internal "\<npweps[0-9:?+]*\c\>"
syntax match gw "\<npwkss[0-9:?+]*\c\>"
syntax match internal "\<npwsigx[0-9:?+]*\c\>"
syntax match internal "\<npwwfn[0-9:?+]*\c\>"
syntax match gstate "\<nqpt[0-9:?+]*\c\>"
syntax match gstate "\<nqfd[0-9:?+]*\c\>"
syntax match gw "\<nqptdm[0-9:?+]*\c\>"
syntax match dev "\<nscforder[0-9:?+]*\c\>"
syntax match basic "\<nshiftk[0-9:?+]*\c\>"
syntax match gstate "\<nshiftq[0-9:?+]*\c\>"
syntax match gstate "\<nspden[0-9:?+]*\c\>"
syntax match gstate "\<nspinor[0-9:?+]*\c\>"
syntax match basic "\<nsppol[0-9:?+]*\c\>"
syntax match basic "\<nstep[0-9:?+]*\c\>"
syntax match basic "\<nsym[0-9:?+]*\c\>"
syntax match rlx "\<ntime[0-9:?+]*\c\>"
syntax match rlx "\<ntimimage[0-9:?+]*\c\>"
syntax match gstate "\<ntypalch[0-9:?+]*\c\>"
syntax match basic "\<ntypat[0-9:?+]*\c\>"
syntax match gstate "\<ntyppure[0-9:?+]*\c\>"
syntax match gstate "\<nucdipmom[0-9:?+]*\c\>"
syntax match paw "\<nucefg[0-9:?+]*\c\>"
syntax match paw "\<nucfc[0-9:?+]*\c\>"
syntax match gstate "\<nwfshist[0-9:?+]*\c\>"
syntax match geo "\<nzchempot[0-9:?+]*\c\>"
syntax match geo "\<objaat[0-9:?+]*\c\>"
syntax match geo "\<objaax[0-9:?+]*\c\>"
syntax match geo "\<objan[0-9:?+]*\c\>"
syntax match geo "\<objarf[0-9:?+]*\c\>"
syntax match geo "\<objaro[0-9:?+]*\c\>"
syntax match geo "\<objatr[0-9:?+]*\c\>"
syntax match geo "\<objbat[0-9:?+]*\c\>"
syntax match geo "\<objbax[0-9:?+]*\c\>"
syntax match geo "\<objbn[0-9:?+]*\c\>"
syntax match geo "\<objbrf[0-9:?+]*\c\>"
syntax match geo "\<objbro[0-9:?+]*\c\>"
syntax match geo "\<objbtr[0-9:?+]*\c\>"
syntax match gstate "\<occ[0-9:?+]*\c\>"
syntax match basic "\<occopt[0-9:?+]*\c\>"
syntax match gw "\<omegasimax[0-9:?+]*\c\>"
syntax match gw "\<omegasrdmax[0-9:?+]*\c\>"
syntax match rlx "\<optcell[0-9:?+]*\c\>"
syntax match gstate "\<optdriver[0-9:?+]*\c\>"
syntax match dev "\<optforces[0-9:?+]*\c\>"
syntax match dev "\<optnlxccc[0-9:?+]*\c\>"
syntax match gstate "\<optstress[0-9:?+]*\c\>"
syntax match dfpt "\<orbmag[0-9:?+]*\c\>"
syntax match dev "\<ortalg[0-9:?+]*\c\>"
syntax match dev "\<papiopt[0-9:?+]*\c\>"
syntax match paral "\<paral_atom[0-9:?+]*\c\>"
syntax match paral "\<paral_kgb[0-9:?+]*\c\>"
syntax match paral "\<paral_rf[0-9:?+]*\c\>"
syntax match paw "\<pawcpxocc[0-9:?+]*\c\>"
syntax match paw "\<pawcross[0-9:?+]*\c\>"
syntax match paw "\<pawecutdg[0-9:?+]*\c\>"
syntax match paw "\<pawfatbnd[0-9:?+]*\c\>"
syntax match paw "\<pawlcutd[0-9:?+]*\c\>"
syntax match paw "\<pawlmix[0-9:?+]*\c\>"
syntax match paw "\<pawmixdg[0-9:?+]*\c\>"
syntax match paw "\<pawnhatxc[0-9:?+]*\c\>"
syntax match paw "\<pawnphi[0-9:?+]*\c\>"
syntax match paw "\<pawntheta[0-9:?+]*\c\>"
syntax match paw "\<pawnzlm[0-9:?+]*\c\>"
syntax match paw "\<pawoptmix[0-9:?+]*\c\>"
syntax match paw "\<pawoptosc[0-9:?+]*\c\>"
syntax match paw "\<pawovlp[0-9:?+]*\c\>"
syntax match dev "\<pawprt_b[0-9:?+]*\c\>"
syntax match dev "\<pawprt_k[0-9:?+]*\c\>"
syntax match paw "\<pawprtden[0-9:?+]*\c\>"
syntax match paw "\<pawprtdos[0-9:?+]*\c\>"
syntax match paw "\<pawprtvol[0-9:?+]*\c\>"
syntax match paw "\<pawprtwf[0-9:?+]*\c\>"
syntax match paw "\<pawspnorb[0-9:?+]*\c\>"
syntax match paw "\<pawstgylm[0-9:?+]*\c\>"
syntax match paw "\<pawsushat[0-9:?+]*\c\>"
syntax match dev "\<pawujat[0-9:?+]*\c\>"
syntax match dev "\<pawujrad[0-9:?+]*\c\>"
syntax match dev "\<pawujv[0-9:?+]*\c\>"
syntax match paw "\<pawusecp[0-9:?+]*\c\>"
syntax match paw "\<pawxcdev[0-9:?+]*\c\>"
syntax match eph "\<ph_intmeth[0-9:?+]*\c\>"
syntax match eph "\<ph_ndivsm[0-9:?+]*\c\>"
syntax match eph "\<ph_ngqpt[0-9:?+]*\c\>"
syntax match eph "\<ph_nqpath[0-9:?+]*\c\>"
syntax match eph "\<ph_nqshift[0-9:?+]*\c\>"
syntax match eph "\<ph_qpath[0-9:?+]*\c\>"
syntax match eph "\<ph_qshift[0-9:?+]*\c\>"
syntax match eph "\<ph_smear[0-9:?+]*\c\>"
syntax match eph "\<ph_wstep[0-9:?+]*\c\>"
syntax match rlx "\<pimass[0-9:?+]*\c\>"
syntax match rlx "\<pimd_constraint[0-9:?+]*\c\>"
syntax match rlx "\<pitransform[0-9:?+]*\c\>"
syntax match dev "\<plowan_bandf[0-9:?+]*\c\>"
syntax match dev "\<plowan_bandi[0-9:?+]*\c\>"
syntax match dev "\<plowan_compute[0-9:?+]*\c\>"
syntax match dev "\<plowan_iatom[0-9:?+]*\c\>"
syntax match dev "\<plowan_it[0-9:?+]*\c\>"
syntax match dev "\<plowan_lcalc[0-9:?+]*\c\>"
syntax match dev "\<plowan_natom[0-9:?+]*\c\>"
syntax match dev "\<plowan_nbl[0-9:?+]*\c\>"
syntax match dev "\<plowan_nt[0-9:?+]*\c\>"
syntax match dev "\<plowan_projcalc[0-9:?+]*\c\>"
syntax match dev "\<plowan_realspace[0-9:?+]*\c\>"
syntax match ffield "\<polcen[0-9:?+]*\c\>"
syntax match gstate "\<posdoppler[0-9:?+]*\c\>"
syntax match gstate "\<positron[0-9:?+]*\c\>"
syntax match gstate "\<posnstep[0-9:?+]*\c\>"
syntax match gstate "\<posocc[0-9:?+]*\c\>"
syntax match gstate "\<postoldfe[0-9:?+]*\c\>"
syntax match gstate "\<postoldff[0-9:?+]*\c\>"
syntax match gw "\<ppmfrq[0-9:?+]*\c\>"
syntax match gw "\<ppmodel[0-9:?+]*\c\>"
syntax match dfpt "\<prepalw[0-9:?+]*\c\>"
syntax match dfpt "\<prepanl[0-9:?+]*\c\>"
syntax match dfpt "\<prepgkk[0-9:?+]*\c\>"
syntax match dev "\<prepscphon[0-9:?+]*\c\>"
syntax match files "\<prt1dm[0-9:?+]*\c\>"
syntax match rlx "\<prtatlist[0-9:?+]*\c\>"
syntax match dfpt "\<prtbbb[0-9:?+]*\c\>"
syntax match dev "\<prtbltztrp[0-9:?+]*\c\>"
syntax match files "\<prtchkprdm[0-9:?+]*\c\>"
syntax match dev "\<prtcif[0-9:?+]*\c\>"
syntax match rttddft "\<prtcurrent[0-9:?+]*\c\>"
syntax match files "\<prtddb[0-9:?+]*\c\>"
syntax match files "\<prtden[0-9:?+]*\c\>"
syntax match gstate "\<prtdensph[0-9:?+]*\c\>"
syntax match dev "\<prtdipole[0-9:?+]*\c\>"
syntax match files "\<prtdos[0-9:?+]*\c\>"
syntax match files "\<prtdosm[0-9:?+]*\c\>"
syntax match gstate "\<prtebands[0-9:?+]*\c\>"
syntax match dfpt "\<prtefmas[0-9:?+]*\c\>"
syntax match files "\<prteig[0-9:?+]*\c\>"
syntax match files "\<prtelf[0-9:?+]*\c\>"
syntax match files "\<prtevk[0-9:?+]*\c\>"
syntax match dfpt "\<prtfull1wf[0-9:?+]*\c\>"
syntax match files "\<prtfsurf[0-9:?+]*\c\>"
syntax match files "\<prtgden[0-9:?+]*\c\>"
syntax match files "\<prtgeo[0-9:?+]*\c\>"
syntax match files "\<prtgkk[0-9:?+]*\c\>"
syntax match files "\<prtgsr[0-9:?+]*\c\>"
syntax match files "\<prthist[0-9:?+]*\c\>"
syntax match files "\<prtkden[0-9:?+]*\c\>"
syntax match files "\<prtkpt[0-9:?+]*\c\>"
syntax match files "\<prtlden[0-9:?+]*\c\>"
syntax match paw "\<prtnabla[0-9:?+]*\c\>"
syntax match eph "\<prtnest[0-9:?+]*\c\>"
syntax match eph "\<prtphbands[0-9:?+]*\c\>"
syntax match eph "\<prtphdos[0-9:?+]*\c\>"
syntax match eph "\<prtphsurf[0-9:?+]*\c\>"
syntax match dev "\<prtposcar[0-9:?+]*\c\>"
syntax match files "\<prtpot[0-9:?+]*\c\>"
syntax match dev "\<prtprocar[0-9:?+]*\c\>"
syntax match files "\<prtpsps[0-9:?+]*\c\>"
syntax match files "\<prtspcur[0-9:?+]*\c\>"
syntax match files "\<prtstm[0-9:?+]*\c\>"
syntax match files "\<prtsuscep[0-9:?+]*\c\>"
syntax match files "\<prtvclmb[0-9:?+]*\c\>"
syntax match vdw "\<prtvdw[0-9:?+]*\c\>"
syntax match files "\<prtvha[0-9:?+]*\c\>"
syntax match files "\<prtvhxc[0-9:?+]*\c\>"
syntax match files "\<prtvol[0-9:?+]*\c\>"
syntax match files "\<prtvolimg[0-9:?+]*\c\>"
syntax match files "\<prtvpsp[0-9:?+]*\c\>"
syntax match files "\<prtvxc[0-9:?+]*\c\>"
syntax match files "\<prtwant[0-9:?+]*\c\>"
syntax match files "\<prtwf[0-9:?+]*\c\>"
syntax match files "\<prtwf_full[0-9:?+]*\c\>"
syntax match gstate "\<prt_lorbmag[0-9:?+]*\c\>"
syntax match files "\<prtxml[0-9:?+]*\c\>"
syntax match paw "\<ptcharge[0-9:?+]*\c\>"
syntax match geo "\<ptgroupma[0-9:?+]*\c\>"
syntax match gw "\<pvelmax[0-9:?+]*\c\>"
syntax match paral "\<pw_unbal_thresh[0-9:?+]*\c\>"
syntax match rlx "\<qmass[0-9:?+]*\c\>"
syntax match ffield "\<qprtrb[0-9:?+]*\c\>"
syntax match gstate "\<qpt[0-9:?+]*\c\>"
syntax match gw "\<qptdm[0-9:?+]*\c\>"
syntax match internal "\<qptn[0-9:?+]*\c\>"
syntax match gstate "\<qptnrm[0-9:?+]*\c\>"
syntax match gstate "\<qptopt[0-9:?+]*\c\>"
syntax match gstate "\<qptrlatt[0-9:?+]*\c\>"
syntax match paw "\<quadmom[0-9:?+]*\c\>"
syntax match rlx "\<random_atpos[0-9:?+]*\c\>"
syntax match gstate "\<ratsm[0-9:?+]*\c\>"
syntax match gstate "\<ratsph[0-9:?+]*\c\>"
syntax match gstate "\<ratsph_extra[0-9:?+]*\c\>"
syntax match gstate "\<rcut[0-9:?+]*\c\>"
syntax match dev "\<recefermi[0-9:?+]*\c\>"
syntax match dev "\<recgratio[0-9:?+]*\c\>"
syntax match dev "\<recnpath[0-9:?+]*\c\>"
syntax match dev "\<recnrec[0-9:?+]*\c\>"
syntax match dev "\<recptrott[0-9:?+]*\c\>"
syntax match dev "\<recrcut[0-9:?+]*\c\>"
syntax match dev "\<rectesteg[0-9:?+]*\c\>"
syntax match dev "\<rectolden[0-9:?+]*\c\>"
syntax match ffield "\<red_dfield[0-9:?+]*\c\>"
syntax match ffield "\<red_efield[0-9:?+]*\c\>"
syntax match ffield "\<red_efieldbar[0-9:?+]*\c\>"
syntax match rlx "\<restartxf[0-9:?+]*\c\>"
syntax match dfpt "\<rf2_dkdk[0-9:?+]*\c\>"
syntax match dfpt "\<rf2_dkde[0-9:?+]*\c\>"
syntax match dfpt "\<rf2_pert1_dir[0-9:?+]*\c\>"
syntax match dfpt "\<rf2_pert2_dir[0-9:?+]*\c\>"
syntax match dfpt "\<rfatpol[0-9:?+]*\c\>"
syntax match dfpt "\<rfddk[0-9:?+]*\c\>"
syntax match dfpt "\<rfdir[0-9:?+]*\c\>"
syntax match dfpt "\<rfelfd[0-9:?+]*\c\>"
syntax match dfpt "\<rfmagn[0-9:?+]*\c\>"
syntax match dfpt "\<rfmeth[0-9:?+]*\c\>"
syntax match dfpt "\<rfphon[0-9:?+]*\c\>"
syntax match dfpt "\<rfstrs[0-9:?+]*\c\>"
syntax match dfpt "\<rfstrs_ref[0-9:?+]*\c\>"
syntax match dfpt "\<rfuser[0-9:?+]*\c\>"
syntax match gw "\<rhoqpmix[0-9:?+]*\c\>"
syntax match basic "\<rprim[0-9:?+]*\c\>"
syntax match basic "\<rprimd[0-9:?+]*\c\>"
syntax match basic "\<scalecart[0-9:?+]*\c\>"
syntax match gstate "\<scphon_supercell[0-9:?+]*\c\>"
syntax match gstate "\<scphon_temp[0-9:?+]*\c\>"
syntax match basic "\<shiftk[0-9:?+]*\c\>"
syntax match gstate "\<shiftq[0-9:?+]*\c\>"
syntax match rlx "\<signperm[0-9:?+]*\c\>"
syntax match gstate "\<slabwsrad[0-9:?+]*\c\>"
syntax match gstate "\<slabzbeg[0-9:?+]*\c\>"
syntax match gstate "\<slabzend[0-9:?+]*\c\>"
syntax match gstate "\<slk_rankpp[0-9:?+]*\c\>"
syntax match dfpt "\<smdelta[0-9:?+]*\c\>"
syntax match gstate "\<so_psp[0-9:?+]*\c\>"
syntax match gw "\<spbroad[0-9:?+]*\c\>"
syntax match geo "\<spgaxor[0-9:?+]*\c\>"
syntax match geo "\<spgorig[0-9:?+]*\c\>"
syntax match geo "\<spgroup[0-9:?+]*\c\>"
syntax match geo "\<spgroupma[0-9:?+]*\c\>"
syntax match gstate "\<spinat[0-9:?+]*\c\>"
syntax match ffield "\<spinmagntarget[0-9:?+]*\c\>"
syntax match gw "\<spmeth[0-9:?+]*\c\>"
syntax match paw "\<spnorbscl[0-9:?+]*\c\>"
syntax match gstate "\<stmbias[0-9:?+]*\c\>"
syntax match rlx "\<strfact[0-9:?+]*\c\>"
syntax match rlx "\<string_algo[0-9:?+]*\c\>"
syntax match rlx "\<strprecon[0-9:?+]*\c\>"
syntax match rlx "\<strtarget[0-9:?+]*\c\>"
syntax match gstate "\<symafm[0-9:?+]*\c\>"
syntax match gw "\<symchi[0-9:?+]*\c\>"
syntax match eph "\<symdynmat[0-9:?+]*\c\>"
syntax match dev "\<symmorphi[0-9:?+]*\c\>"
syntax match basic "\<symrel[0-9:?+]*\c\>"
syntax match gw "\<symsigma[0-9:?+]*\c\>"
syntax match dfpt "\<td_maxene[0-9:?+]*\c\>"
syntax match eph "\<tolcum[0-9:?+]*\c\>"
syntax match dfpt "\<td_mexcit[0-9:?+]*\c\>"
syntax match dev "\<tfkinfunc[0-9:?+]*\c\>"
syntax match dev "\<tfw_toldfe[0-9:?+]*\c\>"
syntax match dfpt "\<tim1rev[0-9:?+]*\c\>"
syntax match gstate "\<timopt[0-9:?+]*\c\>"
syntax match gstate "\<tl_nprccg[0-9:?+]*\c\>"
syntax match gstate "\<tl_radius[0-9:?+]*\c\>"
syntax match basic "\<tnons[0-9:?+]*\c\>"
syntax match basic "\<toldfe[0-9:?+]*\c\>"
syntax match basic "\<toldff[0-9:?+]*\c\>"
syntax match rlx "\<tolimg[0-9:?+]*\c\>"
syntax match rlx "\<tolmxde[0-9:?+]*\c\>"
syntax match rlx "\<tolmxf[0-9:?+]*\c\>"
syntax match dev "\<tolrde[0-9:?+]*\c\>"
syntax match basic "\<tolrff[0-9:?+]*\c\>"
syntax match geo "\<tolsym[0-9:?+]*\c\>"
syntax match basic "\<tolvrs[0-9:?+]*\c\>"
syntax match basic "\<tolwfr[0-9:?+]*\c\>"
syntax match basic "\<tolwfr_diago[0-9:?+]*\c\>"
syntax match gstate "\<tphysel[0-9:?+]*\c\>"
syntax match gstate "\<tsmear[0-9:?+]*\c\>"
syntax match basic "\<typat[0-9:?+]*\c\>"
syntax match gw "\<ucrpa[0-9:?+]*\c\>"
syntax match gw "\<ucrpa_bands[0-9:?+]*\c\>"
syntax match gw "\<ucrpa_window[0-9:?+]*\c\>"
syntax match basic "\<udtset[0-9:?+]*\c\>"
syntax match paw "\<upawu[0-9:?+]*\c\>"
syntax match dev "\<use_gemm_nonlop[0-9:?+]*\c\>"
syntax match dev "\<use_nonscf_gkk[0-9:?+]*\c\>"
syntax match paral "\<use_slk[0-9:?+]*\c\>"
syntax match paw "\<usedmatpu[0-9:?+]*\c\>"
syntax match dev "\<usedmft[0-9:?+]*\c\>"
syntax match paw "\<useexexch[0-9:?+]*\c\>"
syntax match internal "\<usefock[0-9:?+]*\c\>"
syntax match gstate "\<usekden[0-9:?+]*\c\>"
syntax match internal "\<usepaw[0-9:?+]*\c\>"
syntax match paw "\<usepawu[0-9:?+]*\c\>"
syntax match dfpt "\<usepead[0-9:?+]*\c\>"
syntax match dev "\<usepotzero[0-9:?+]*\c\>"
syntax match internal "\<userec[0-9:?+]*\c\>"
syntax match dev "\<useria[0-9:?+]*\c\>"
syntax match dev "\<userib[0-9:?+]*\c\>"
syntax match dev "\<useric[0-9:?+]*\c\>"
syntax match dev "\<userid[0-9:?+]*\c\>"
syntax match dev "\<userie[0-9:?+]*\c\>"
syntax match dev "\<userra[0-9:?+]*\c\>"
syntax match dev "\<userrb[0-9:?+]*\c\>"
syntax match dev "\<userrc[0-9:?+]*\c\>"
syntax match dev "\<userrd[0-9:?+]*\c\>"
syntax match dev "\<userre[0-9:?+]*\c\>"
syntax match basic "\<usewvl[0-9:?+]*\c\>"
syntax match paw "\<usexcnhat[0-9:?+]*\c\>"
syntax match dev "\<useylm[0-9:?+]*\c\>"
syntax match geo "\<vaclst[0-9:?+]*\c\>"
syntax match geo "\<vacnum[0-9:?+]*\c\>"
syntax match gstate "\<vacuum[0-9:?+]*\c\>"
syntax match gstate "\<vacwidth[0-9:?+]*\c\>"
syntax match gstate "\<vcutgeo[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_acutmin[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_aratio[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_damax[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_damin[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_dcut[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_dratio[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_dsoft[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_gcut[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_ndpts[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_ngpts[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_nqpts[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_nrpts[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_nsmooth[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_phisoft[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_qcut[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_qratio[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_rcut[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_rsoft[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_threshold[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_tolerance[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_tweaks[0-9:?+]*\c\>"
syntax match vdw "\<vdw_df_zab[0-9:?+]*\c\>"
syntax match vdw "\<vdw_nfrag[0-9:?+]*\c\>"
syntax match vdw "\<vdw_supercell[0-9:?+]*\c\>"
syntax match vdw "\<vdw_tol[0-9:?+]*\c\>"
syntax match vdw "\<vdw_tol_3bt[0-9:?+]*\c\>"
syntax match vdw "\<vdw_typfrag[0-9:?+]*\c\>"
syntax match vdw "\<vdw_xc[0-9:?+]*\c\>"
syntax match rlx "\<vel[0-9:?+]*\c\>"
syntax match rlx "\<vel_cell[0-9:?+]*\c\>"
syntax match rlx "\<vis[0-9:?+]*\c\>"
syntax match dev "\<vloc_rcut[0-9:?+]*\c\>"
syntax match ffield "\<vprtrb[0-9:?+]*\c\>"
syntax match w90 "\<w90iniprj[0-9:?+]*\c\>"
syntax match w90 "\<w90prtunk[0-9:?+]*\c\>"
syntax match gstate "\<wfinit[0-9:?+]*\c\>"
syntax match gstate "\<wfmix[0-9:?+]*\c\>"
syntax match dev "\<wfoptalg[0-9:?+]*\c\>"
syntax match files "\<write_files[0-9:?+]*\c\>"
syntax match rlx "\<wtatcon[0-9:?+]*\c\>"
syntax match basic "\<wtk[0-9:?+]*\c\>"
syntax match gstate "\<wtq[0-9:?+]*\c\>"
syntax match gstate "\<wvl_bigdft_comp[0-9:?+]*\c\>"
syntax match gstate "\<wvl_crmult[0-9:?+]*\c\>"
syntax match gstate "\<wvl_frmult[0-9:?+]*\c\>"
syntax match basic "\<wvl_hgrid[0-9:?+]*\c\>"
syntax match gstate "\<wvl_ngauss[0-9:?+]*\c\>"
syntax match gstate "\<wvl_nprccg[0-9:?+]*\c\>"
syntax match gw "\<x1rdm[0-9:?+]*\c\>"
syntax match dev "\<xc_denpos[0-9:?+]*\c\>"
syntax match dev "\<xc_taupos[0-9:?+]*\c\>"
syntax match dev "\<xc_tb09_c[0-9:?+]*\c\>"
syntax match basic "\<xcart[0-9:?+]*\c\>"
syntax match internal "\<xclevel[0-9:?+]*\c\>"
syntax match basic "\<xred[0-9:?+]*\c\>"
syntax match gstate "\<xredsph_extra[0-9:?+]*\c\>"
syntax match geo "\<xyzfile[0-9:?+]*\c\>"
syntax match gw "\<zcut[0-9:?+]*\c\>"
syntax match ffield "\<zeemanfield[0-9:?+]*\c\>"
syntax match internal "\<ziontypat[0-9:?+]*\c\>"
syntax match basic "\<znucl[0-9:?+]*\c\>"
syntax match eph "\<tmesh[0-9:?+]*\c\>"
syntax match files "\<prtkbff[0-9:?+]*\c\>"
syntax match gw "\<sigma_ngkpt[0-9:?+]*\c\>"
syntax match gw "\<sigma_nshiftk[0-9:?+]*\c\>"
syntax match gw "\<sigma_shiftk[0-9:?+]*\c\>"
syntax match rttddft "\<td_ef_type[0-9:?+]*\c\>"
syntax match rttddft "\<td_ef_tzero[0-9:?+]*\c\>"
syntax match rttddft "\<td_ef_ezero[0-9:?+]*\c\>"
syntax match rttddft "\<td_ef_pol[0-9:?+]*\c\>"
syntax match rttddft "\<td_ef_induced_vecpot[0-9:?+]*\c\>"
syntax match rttddft "\<td_exp_order[0-9:?+]*\c\>"
syntax match rttddft "\<td_propagator[0-9:?+]*\c\>"
syntax match rttddft "\<td_prtstr[0-9:?+]*\c\>"
syntax match rttddft "\<td_restart[0-9:?+]*\c\>"
syntax match rttddft "\<td_scnmax[0-9:?+]*\c\>"
syntax match rttddft "\<td_scthr[0-9:?+]*\c\>"
syntax match gstate "\<wfk_task[0-9:?+]*\c\>"
syntax match gw "\<sigma_bsum_range[0-9:?+]*\c\>"
syntax match eph "\<prteliash[0-9:?+]*\c\>"
syntax match eph "\<sigma_erange[0-9:?+]*\c\>"
syntax match eph "\<eph_tols_idelta[0-9:?+]*\c\>"
syntax match eph "\<eph_phrange[0-9:?+]*\c\>"
syntax match eph "\<eph_phrange_w[0-9:?+]*\c\>"
syntax match eph "\<transport_ngkpt[0-9:?+]*\c\>"
syntax match eph "\<ibte_abs_tol[0-9:?+]*\c\>"
syntax match eph "\<ibte_alpha_mix[0-9:?+]*\c\>"
syntax match eph "\<ibte_niter[0-9:?+]*\c\>"
syntax match eph "\<ibte_prep[0-9:?+]*\c\>"
syntax match eph "\<eph_prtscratew[0-9:?+]*\c\>"
syntax match eph "\<eph_restart[0-9:?+]*\c\>"
syntax match eph "\<eph_stern[0-9:?+]*\c\>"
syntax match eph "\<getkerange_filepath[0-9:?+]*\c\>"
syntax match eph "\<symv1scf[0-9:?+]*\c\>"
syntax match eph "\<dvdb_add_lr[0-9:?+]*\c\>"
syntax match eph "\<eph_np_pqbks[0-9:?+]*\c\>"
syntax match eph "\<eph_use_ftinterp[0-9:?+]*\c\>"
syntax match files "\<getpot_filepath[0-9:?+]*\c\>"
syntax match files "\<getwfk_filepath[0-9:?+]*\c\>"
syntax match files "\<getwfkfine_filepath[0-9:?+]*\c\>"
syntax match files "\<getwfq_filepath[0-9:?+]*\c\>"
syntax match files "\<getddb_filepath[0-9:?+]*\c\>"
syntax match files "\<getdvdb_filepath[0-9:?+]*\c\>"
syntax match files "\<getden_filepath[0-9:?+]*\c\>"
syntax match files "\<getscr_filepath[0-9:?+]*\c\>"
syntax match eph "\<eph_ecutosc[0-9:?+]*\c\>"
syntax match files "\<output_file[0-9:?+]*\c\>"
syntax match files "\<indata_prefix[0-9:?+]*\c\>"
syntax match files "\<outdata_prefix[0-9:?+]*\c\>"
syntax match files "\<tmpdata_prefix[0-9:?+]*\c\>"
syntax match files "\<pp_dirpath[0-9:?+]*\c\>"
syntax match gstate "\<supercell_latt[0-9:?+]*\c\>"
syntax match files "\<pseudos[0-9:?+]*\c\>"
syntax match basic "\<structure[0-9:?+]*\c\>"
syntax match eph "\<dvdb_rspace_cell[0-9:?+]*\c\>"
syntax match eph "\<dvdb_qdamp[0-9:?+]*\c\>"
syntax match files "\<getsigeph_filepath[0-9:?+]*\c\>"
syntax match eph "\<brav[0-9:?+]*\c\>"
syntax match eph "\<eph_doping[0-9:?+]*\c\>"
syntax match eph "\<eph_phwinfact[0-9:?+]*\c\>"
syntax match eph "\<rifcsph[0-9:?+]*\c\>"
syntax match gstate "\<rmm_diis[0-9:?+]*\c\>"
syntax match gstate "\<rmm_diis_savemem[0-9:?+]*\c\>"
syntax match gstate "\<useextfpmd[0-9:?+]*\c\>"
syntax match gstate "\<extfpmd_nband[0-9:?+]*\c\>"
syntax match gstate "\<extfpmd_nbcut[0-9:?+]*\c\>"
syntax match gstate "\<extfpmd_nbdbuf[0-9:?+]*\c\>"
syntax match eph "\<dipquad[0-9:?+]*\c\>"
syntax match eph "\<quadquad[0-9:?+]*\c\>"
syntax match gw "\<use_oldchi[0-9:?+]*\c\>"
syntax match eph "\<gstore_cplex[0-9:?+]*\c\>"
syntax match eph "\<gstore_with_vk[0-9:?+]*\c\>"
syntax match eph "\<gstore_kzone[0-9:?+]*\c\>"
syntax match eph "\<gstore_qzone[0-9:?+]*\c\>"
syntax match eph "\<gstore_kfilter[0-9:?+]*\c\>"
syntax match eph "\<gstore_gmode[0-9:?+]*\c\>"
syntax match eph "\<gstore_brange[0-9:?+]*\c\>"
syntax match eph "\<getgstore_filepath[0-9:?+]*\c\>"
syntax match eph "\<getabiwan_filepath[0-9:?+]*\c\>"
syntax match eph "\<getabiwan[0-9:?+]*\c\>"
syntax match eph "\<getgwan_filepath[0-9:?+]*\c\>"
syntax match eph "\<getgwan[0-9:?+]*\c\>"
syntax match eph "\<gstore_erange[0-9:?+]*\c\>"
syntax match gwr "\<gwr_np_kgts[0-9:?+]*\c\>"
syntax match gwr "\<gwr_ucsc_batch[0-9:?+]*\c\>"
syntax match gwr "\<gwr_task[0-9:?+]*\c\>"
syntax match gwr "\<gwr_ntau[0-9:?+]*\c\>"
syntax match gwr "\<gwr_chi_algo[0-9:?+]*\c\>"
syntax match gwr "\<gwr_rpa_ncut[0-9:?+]*\c\>"
syntax match gwr "\<gwr_sigma_algo[0-9:?+]*\c\>"
syntax match gwr "\<gwr_boxcutmin[0-9:?+]*\c\>"
syntax match gwr "\<gwr_max_hwtene[0-9:?+]*\c\>"
syntax match gwr "\<gwr_regterm[0-9:?+]*\c\>"
syntax match paw "\<optdcmagpawu[0-9:?+]*\c\>"
syntax match eph "\<gwpt_np_wpqbks[0-9:?+]*\c\>"
syntax match dev "\<xg_nonlop_option[0-9:?+]*\c\>"
syntax match files "\<getdrhodb[0-9:?+]*\c\>"
syntax match files "\<getdrhodb_filepath[0-9:?+]*\c\>"
syntax match files "\<irddrhodb[0-9:?+]*\c\>"
syntax match eph "\<getvpq_filepath[0-9:?+]*\c\>"
syntax match eph "\<getvpq[0-9:?+]*\c\>"
syntax match eph "\<vpq_aseed[0-9:?+]*\c\>"
syntax match eph "\<vpq_pkind[0-9:?+]*\c\>"
syntax match eph "\<vpq_avg_g[0-9:?+]*\c\>"
syntax match eph "\<vpq_interp[0-9:?+]*\c\>"
syntax match eph "\<vpq_nstates[0-9:?+]*\c\>"
syntax match eph "\<vpq_nstep[0-9:?+]*\c\>"
syntax match eph "\<vpq_select[0-9:?+]*\c\>"
syntax match eph "\<vpq_mesh_fact[0-9:?+]*\c\>"
syntax match eph "\<vpq_tolgrs[0-9:?+]*\c\>"
syntax match eph "\<vpq_gpr_energy[0-9:?+]*\c\>"
syntax match eph "\<vpq_trvec[0-9:?+]*\c\>"
syntax match eph "\<vpq_gpr_length[0-9:?+]*\c\>"
syntax match eph "\<vpq_translate[0-9:?+]*\c\>"
syntax match eph "\<vpq_nstep_ort[0-9:?+]*\c\>"
syntax match eph "\<vpq_mix_fact[0-9:?+]*\c\>"
syntax match eph "\<eph_fix_korq[0-9:?+]*\c\>"
syntax match eph "\<eph_fix_wavevec[0-9:?+]*\c\>"
syntax match eph "\<eph_path_brange[0-9:?+]*\c\>"
syntax match gstate "\<oracle_factor[0-9:?+]*\c\>"
syntax match gstate "\<oracle_min_occ[0-9:?+]*\c\>"

" ============================

syntax match Comment "[#!].*"
if g:abivim_supercomment
    exec 'highlight BrightComment guifg= ' . g:abivim_color_supercomment
    syntax match BrightComment "##.*"
endif
